"""Summarize UPMEM/CPU median-time ratios over exactly seven common widths."""
import csv
import json
import math
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import PRIMARY_FAMILIES, TABLE_OUTPUT, V4_READOUT, V4_RESULTS  # noqa: E402


SOURCE_BASE = "https://github.com/kazulak/masters-thesis/blob/c7c6cac0b55bdff2f4c24b70397b36f89bedc45f/"
CPU_ROLES = ("quest32_p8", "quest32_p1", "numpy_f32_p1")
UPMEM_ROLES = ("upmem_f32", "upmem_int8")


def geometric_mean(values):
    if not values or not all(math.isfinite(v) and v > 0 for v in values):
        raise ValueError("Ratios must be positive, finite and nonempty")
    return math.exp(sum(math.log(v) for v in values) / len(values))


def build_rows():
    manifest = json.loads((V4_RESULTS / "manifest/manifest.json").read_text())
    cases = {c["case_id"]: c for c in manifest["cases"]}
    with (V4_READOUT / "W.csv").open(newline="") as stream:
        readout = list(csv.DictReader(stream))
    supported = {}
    for row in readout:
        case = cases[row["case_id"]]
        if case["cohort"] != "primary" or row["view"] != "W" or row["role"] not in UPMEM_ROLES + CPU_ROLES:
            raise ValueError(f"Unexpected width-readout row: {row['case_id']}")
        key = (case["family"], row["role"], case["n"])
        value = float(row["median_job_to_state_cached_path_s"])
        if key in supported or int(row["count"]) != 5 or not math.isfinite(value) or value <= 0:
            raise ValueError(f"Missing, duplicate or invalid width median: {key}")
        supported[key] = value
    rows = []
    for family in PRIMARY_FAMILIES:
        width_sets = [{n for f, role, n in supported if f == family and role == arm} for arm in UPMEM_ROLES + CPU_ROLES]
        common = tuple(sorted(set.intersection(*width_sets)))
        expected = (7, 11, 15, 17, 19, 21, 23) if family == "edc" else (8, 12, 16, 18, 20, 22, 24)
        if common != expected:
            raise ValueError(f"Unexpected common supported widths for {family}: {common}")
        for policy in UPMEM_ROLES:
            ratios = {}
            for cpu in CPU_ROLES:
                per_width = [supported[(family, policy, n)] / supported[(family, cpu, n)] for n in common]
                ratios[cpu] = geometric_mean(per_width)
            rows.append(dict(family=family, policy=policy, widths=common, ratios=ratios))
    for policy in UPMEM_ROLES:
        family_rows = [row for row in rows if row["policy"] == policy]
        if len(family_rows) != 6:
            raise ValueError("Overall CPU comparison needs six equally weighted families")
        ratios = {cpu: geometric_mean([row["ratios"][cpu] for row in family_rows]) for cpu in CPU_ROLES}
        rows.append(dict(family="overall", policy=policy, widths="7 / family", ratios=ratios))
    return rows


def cell(value):
    return "[" + " #linebreak() ".join("#text(" + json.dumps(str(line), ensure_ascii=False) + ")" for line in str(value).split("\n")) + "]"


def ratio_label(value):
    exponent = math.floor(math.log10(value))
    number = f"{value:.2e}" if exponent < -3 or exponent >= 3 else f"{value:.{2 - exponent}f}"
    return number + "×"


def main():
    rows = build_rows()
    header = ["Family", "UPMEM policy", "Widths n", "QuEST P8", "QuEST P1", "NumPy\nsame DAG"]
    lines = ["// Generated by table05_cpu_comparison.py; no new confidence interval is computed.", "#[", "#set text(size: 8pt)",
             "#set par(leading: 0.5em)", "#table(", "  columns: (18mm, 24mm, 49mm, 23mm, 23mm, 23mm),",
             "  align: (left, left, right, right, right, right),", "  stroke: none, inset: (x: 2pt, y: 4pt),",
             "  table.hline(stroke: 0.6pt),", "  table.header(repeat: true, " + ", ".join(cell(v) for v in header) + "),", "  table.hline(stroke: 0.4pt),"]
    for row in rows:
        widths = ", ".join(str(n) for n in row["widths"]) if isinstance(row["widths"], tuple) else row["widths"]
        values = [row["family"].upper() if row["family"] != "overall" else "Overall", "Float32" if row["policy"] == "upmem_f32" else "Int8 (approx.)", widths]
        values += [ratio_label(row["ratios"][cpu]) for cpu in CPU_ROLES]
        lines.append("  " + ", ".join(cell(v) for v in values) + ",")
    notes = [
        "Notes: Ratios are UPMEM time / CPU-reference time; values above 1 mean UPMEM is slower. This table summarizes all seven common supported widths, including small cases; it does not represent only the largest width. For each family and policy, divide the five-block median UPMEM time by the corresponding CPU median separately at each listed width, then take their geometric mean. Overall rows give each of the six families equal weight. No new confidence interval is estimated.",
        "Timing is cached-path job-to-state latency, excluding one-off path search. QuEST P8 and P1 request eight and one CPU threads, respectively; NumPy uses one thread and the same selected tensor-contraction DAG. Float32 and approximate int8 UPMEM use their independently frozen per-family resource choices, so resources can differ between policies. The int8 comparisons report approximate execution, not an exact-float32 accuracy equivalence.",
    ]
    lines += ["  table.hline(stroke: 0.6pt),", ")", "#v(3pt)"]
    for note in notes:
        lines += ["#text(" + json.dumps(note, ensure_ascii=False) + ")", "#parbreak()"]
    for label, path in [("Final width medians", "thesis/implementation/thesis_results/unified_final_v4/readout/W.csv"),
                        ("Frozen resources", "thesis/implementation/thesis_results/unified_final_v4/selection.json"),
                        ("Timing protocol", "evaluation/unified_v4/protocol.json")]:
        lines.append("#link(" + json.dumps(SOURCE_BASE + path) + ", " + json.dumps(label) + ") ")
    lines.append("]\n")
    TABLE_OUTPUT.mkdir(parents=True, exist_ok=True)
    (TABLE_OUTPUT / "table05_cpu_comparison.typ").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
