"""Describe the six frozen family definitions and verify their width mapping."""
import hashlib
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import PRIMARY_FAMILIES, ROOT, TABLE_OUTPUT, V4_RESULTS  # noqa: E402


SOURCE_BASE = "https://github.com/kazulak/masters-thesis/blob/c7c6cac0b55bdff2f4c24b70397b36f89bedc45f/"
DEFINITIONS = {
    "bb84": ("BB84 state preparation: alternating bits and a two-wire basis cycle.", "n_qubits = a", "n = a"),
    "bv": ("Bernstein–Vazirani: alternating nonzero secret, phase kickback and one oracle ancilla.", "data_qubits = d", "n = d + 1"),
    "edc": ("Repetition-code error detection: encoded data, one X error and coherent adjacent-parity syndromes.", "data_qubits = d", "n = 2d − 1"),
    "hs": ("Hidden shift: pinned QASMBench pair circuit, repeated on disjoint pairs of allocated wires.", "allocated_qubits = a", "n = a; a even"),
    "qrng": ("Quantum random-number state preparation: one Hadamard per wire.", "n_qubits = a", "n = a"),
    "xor": ("XOR parity: Hadamards on data wires followed by CNOTs to one parity ancilla.", "data_qubits = d", "n = d + 1"),
}


def build_rows():
    manifest = json.loads((V4_RESULTS / "manifest/manifest.json").read_text())
    config_path = ROOT / "thesis/implementation/configs/upmem_family_aligned_workload_v1.json"
    config = json.loads(config_path.read_text())
    constructor = config["provenance"]["constructor_source"]
    if hashlib.sha256((ROOT / constructor["path"]).read_bytes()).hexdigest() != constructor["sha256"]:
        raise ValueError("Constructor differs from the frozen workload definition")
    if config["scope"]["exact_pimutation_instances_verified"] is not False:
        raise ValueError("Reassess the instance-reproduction qualification")
    if set(config["scope"]["families"]) != {f.upper() for f in PRIMARY_FAMILIES}:
        raise ValueError("Unexpected primary family scope")
    for instance in config["instances"]:
        family, parameters = instance["family_key"], instance["family_parameters"]
        if family in {"bv", "xor"}:
            actual = parameters["data_qubits"] + 1
        elif family == "edc":
            actual = 2 * parameters["data_qubits"] - 1
        elif family == "hs":
            actual = parameters["allocated_qubits"]
        else:
            actual = parameters["n_qubits"]
        if actual != instance["widths"]["total_qubits"] or actual != instance["canonical_circuit"]["n_qubits"]:
            raise ValueError(f"Frozen definition width mismatch: {instance['instance_id']}")
    cases = [c for c in manifest["cases"] if c["cohort"] == "primary"]
    if len(cases) != 48 or len({c["case_id"] for c in cases}) != len(cases):
        raise ValueError("Expected 48 distinct primary manifest cases")
    calibration_ids = {c["case_id"] for c in manifest["calibration_cells"]}
    rows = []
    for family in PRIMARY_FAMILIES:
        family_cases = [c for c in cases if c["family"] == family]
        if {c["q"] for c in family_cases} != {8, 12, 16, 18, 20, 22, 24, 26}:
            raise ValueError(f"Unexpected width slots for {family}")
        for case in family_cases:
            parameter = "data_qubits" if family in {"bv", "edc", "xor"} else ("allocated_qubits" if family == "hs" else "n_qubits")
            if set(case["parameters"]) != {parameter} or case["builder"] != "build_family_qasm":
                raise ValueError(f"Unexpected constructor parameters: {case['case_id']}")
            value = case["parameters"][parameter]
            actual = 2 * value - 1 if family == "edc" else value + 1 if family in {"bv", "xor"} else value
            if actual != case["n"] or actual != case["q"] - (family == "edc"):
                raise ValueError(f"Width mapping mismatch: {case['case_id']}")
            if family == "hs" and actual % 2:
                raise ValueError("HS needs an even number of allocated wires")
        calibration = [c for c in family_cases if c["case_id"] in calibration_ids]
        if len(calibration) != 1 or calibration[0]["n"] != (17 if family == "edc" else 18):
            raise ValueError(f"Unexpected calibration case for {family}")
        meaning, parameter, formula = DEFINITIONS[family]
        rows.append(dict(family=family, meaning=meaning, parameter=parameter, formula=formula,
                         calibration_case=calibration[0]["case_id"], calibration_n=calibration[0]["n"]))
    return rows


def cell(value):
    return "[" + " #linebreak() ".join("#text(" + json.dumps(str(line), ensure_ascii=False) + ")" for line in str(value).split("\n")) + "]"


def main():
    rows = build_rows()
    header = ["Family", "Meaning and frozen construction", "Constructor parameter", "Actual width", "Calibration case"]
    lines = ["// Generated by table01_workloads.py; canonical evidence is read directly.", "#[", "#set text(size: 8pt)",
             "#set par(leading: 0.5em)", "#table(", "  columns: (13mm, 62mm, 32mm, 25mm, 28mm),",
             "  align: (left, left, left, left, right),", "  stroke: none, inset: (x: 2pt, y: 4pt),",
             "  table.hline(stroke: 0.6pt),", "  table.header(repeat: true, " + ", ".join(cell(v) for v in header) + "),",
             "  table.hline(stroke: 0.4pt),"]
    for row in rows:
        values = [row["family"].upper(), row["meaning"], row["parameter"], row["formula"], f"{row['calibration_case']}\nn = {row['calibration_n']}"]
        lines.append("  " + ", ".join(cell(v) for v in values) + ",")
    lines += ["  table.hline(stroke: 0.6pt),", ")", "#v(3pt)", "#text(" + json.dumps(
        "Notes: n is the actual allocated state-vector width. a denotes allocated wires; d denotes data wires. BV and XOR add one ancilla; EDC adds d − 1 syndrome wires. Calibration uses the largest family case under the 18-qubit ceiling. All definitions are pre-measurement unitaries with one repeat layer. These are family-aligned definitions; exact PIMutation instance reproduction was not verified.", ensure_ascii=False) + ")", "#parbreak()"]
    for label, path in [("Workload manifest", "thesis/implementation/thesis_results/unified_final_v4/manifest/manifest.json"),
                        ("Constructor", "thesis/implementation/scripts/upmem_family_workload.py"),
                        ("Frozen definitions", "thesis/implementation/configs/upmem_family_aligned_workload_v1.json")]:
        lines.append("#link(" + json.dumps(SOURCE_BASE + path) + ", " + json.dumps(label) + ") ")
    lines.append("]\n")
    TABLE_OUTPUT.mkdir(parents=True, exist_ok=True)
    (TABLE_OUTPUT / "table01_workloads.typ").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
