"""Display the accepted fixed-family path contrasts and their existing intervals."""
import csv
import json
import math
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import PATH_RESULTS, PRIMARY_FAMILIES, TABLE_OUTPUT  # noqa: E402


SOURCE_BASE = "https://github.com/kazulak/masters-thesis/blob/c7c6cac0b55bdff2f4c24b70397b36f89bedc45f/"
METHODS = {"G": "Greedy (G)", "F": "FLOP search (F)", "R": "UPMEM cost reranking (R)", "U": "UPMEM-guided search (U)"}


def build_rows():
    readout = PATH_RESULTS / "readout"
    provenance = json.loads((readout / "provenance.json").read_text())
    if provenance["bootstrap_draws"] != 10000 or len(provenance["profile"]["evaluation_cells"]) != 12:
        raise ValueError("Unexpected accepted bootstrap or evaluation scope")
    with (readout / "aggregates.csv").open(newline="") as stream:
        aggregates = [r for r in csv.DictReader(stream) if r["metric"] == "session_inclusive_s" and r["contrast"] in {"G/F", "F/R", "R/U", "G/U"}]
    lookup = {}
    for row in aggregates:
        key = (row["contrast"], row["group"])
        if key in lookup:
            raise ValueError(f"Duplicate accepted aggregate: {key}")
        lookup[key] = row
    expected = {(contrast, group) for contrast in ("G/F", "F/R", "R/U", "G/U") for group in ("1dpu_t8", "4dpu_t8", "all")}
    if set(lookup) != expected:
        raise ValueError("Incomplete accepted path-contrast matrix")
    with (readout / "methods.csv").open(newline="") as stream:
        methods = list(csv.DictReader(stream))
    method_lookup = {}
    for row in methods:
        key = (row["family"].lower(), row["topology_id"], row["method"])
        value = float(row["session_inclusive_s_median"])
        if key in method_lookup or int(row["n"]) != 5 or not math.isfinite(value) or value <= 0:
            raise ValueError(f"Invalid accepted method median: {key}")
        method_lookup[key] = value
    if set(method_lookup) != {(f, t, m) for f in PRIMARY_FAMILIES for t in ("1dpu_t8", "4dpu_t8") for m in METHODS}:
        raise ValueError("Incomplete accepted method coverage")
    rows = []
    for contrast in ("G/F", "F/R", "R/U", "G/U"):
        reference, method = contrast.split("/")
        result = dict(contrast=contrast, method=METHODS[method], reference=METHODS[reference])
        for group in ("1dpu_t8", "4dpu_t8", "all"):
            record = lookup[(contrast, group)]
            ratio = float(record["family_balanced_geometric_ratio"])
            low, high = float(record["paired_bootstrap_low"]), float(record["paired_bootstrap_high"])
            if not all(math.isfinite(v) and v > 0 for v in (ratio, low, high)) or low > high:
                raise ValueError(f"Invalid accepted estimate/interval: {contrast}, {group}")
            topologies = ("1dpu_t8", "4dpu_t8") if group == "all" else (group,)
            ratios = [method_lookup[(f, t, reference)] / method_lookup[(f, t, method)] for f in PRIMARY_FAMILIES for t in topologies]
            direct = math.exp(sum(math.log(r) for r in ratios) / len(ratios))
            if int(record["cells"]) != len(ratios) or int(record["families"]) != 6 or not math.isclose(ratio, direct, rel_tol=1e-12):
                raise ValueError(f"Accepted point estimate disagrees with method medians: {contrast}, {group}")
            result[group] = dict(ratio=ratio, low=low, high=high)
        rows.append(result)
    return rows


def cell(value):
    return "[" + " #linebreak() ".join("#text(" + json.dumps(str(line), ensure_ascii=False) + ")" for line in str(value).split("\n")) + "]"


def main():
    rows = build_rows()
    header = ["Evaluated method", "Reference", "1 DPU\n8 tasklets", "4 DPUs\n8 tasklets", "Overall"]
    lines = ["// Generated by table04_path_selection.py; accepted intervals are reused unchanged.", "#[", "#set text(size: 8pt)",
             "#set par(leading: 0.5em)", "#table(", "  columns: (37mm, 36mm, 29mm, 29mm, 29mm),",
             "  align: (left, left, right, right, right),", "  stroke: none, inset: (x: 2pt, y: 4pt),",
             "  table.hline(stroke: 0.6pt),", "  table.header(repeat: true, " + ", ".join(cell(v) for v in header) + "),", "  table.hline(stroke: 0.4pt),"]
    for row in rows:
        values = [row["method"], row["reference"]]
        for group in ("1dpu_t8", "4dpu_t8", "all"):
            estimate = row[group]
            values.append(f"{estimate['ratio']:.3f}×\n[{estimate['low']:.3f}, {estimate['high']:.3f}]")
        lines.append("  " + ", ".join(cell(v) for v in values) + ",")
    notes = [
        "Notes: Entries are reference time / evaluated-method time (G/F, F/R, R/U and G/U); values above 1 favor the evaluated method. All runs use float32, 8 tasklets per DPU, complex fusion and static DAG scheduling. Session-inclusive execution includes opening and closing the device session; it excludes search and planning and is not full job-to-state time.",
        "G is deterministic greedy; F searches using a FLOP objective; R reranks the F candidate pool with the frozen UPMEM cost model; U uses the UPMEM objective during search. The overall ratio is the equal-family geometric mean across six families × two topologies. Evaluation uses held-out instances of the same six families, not held-out families.",
        "Brackets show the accepted descriptive 95% paired-bootstrap interval: five complete timing blocks, 10,000 common block resamples, fixed circuits and one paired search-seed schedule. The overall R/U interval spans 1, so these measurements do not resolve an added benefit of UPMEM-guided search beyond reranking; this is not evidence of equivalence or broad optimizer-seed robustness.",
    ]
    lines += ["  table.hline(stroke: 0.6pt),", ")", "#v(3pt)"]
    for note in notes:
        lines += ["#text(" + json.dumps(note, ensure_ascii=False) + ")", "#parbreak()"]
    for label, name in [("Accepted path aggregates", "aggregates.csv"), ("Method medians", "methods.csv"), ("Bootstrap provenance", "provenance.json")]:
        path = "thesis/implementation/thesis_results/upmem_cost_guided_path_v1/readout/" + name
        lines.append("#link(" + json.dumps(SOURCE_BASE + path) + ", " + json.dumps(label) + ") ")
    lines.append("]\n")
    TABLE_OUTPUT.mkdir(parents=True, exist_ok=True)
    (TABLE_OUTPUT / "table04_path_selection.typ").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
