#!/usr/bin/env python3
"""Deterministic publication figures and Typst tables for unified-final-v4.

Reads exclusively from canonical published data under:
  thesis/implementation/thesis_results/unified_final_v4/
Outputs figures (SVG+PNG) and Typst tables (.typ) under:
  thesis/synthesis/unified_v4/
"""
from __future__ import annotations

import ast
import csv
import hashlib
import json
import math
import os
from pathlib import Path
import sys

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

# Styling configuration adhering to thesis publication standard
matplotlib.rcdefaults()
matplotlib.rcParams.update({
    'font.family': 'sans-serif',
    'font.sans-serif': ['DejaVu Sans', 'Arial', 'Helvetica'],
    'font.size': 8.5,
    'axes.titlesize': 9.5,
    'axes.labelsize': 8.5,
    'xtick.labelsize': 7.5,
    'ytick.labelsize': 7.5,
    'legend.fontsize': 7.5,
    'figure.titlesize': 10.5,
    'svg.hashsalt': 'masters-thesis-unified-v4',
    'svg.fonttype': 'path',
    'savefig.dpi': 200,
    'figure.dpi': 100,
})

REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
CANONICAL_DIR = REPO_ROOT / 'thesis' / 'implementation' / 'thesis_results' / 'unified_final_v4'
SYNTHESIS_DIR = REPO_ROOT / 'thesis' / 'synthesis' / 'unified_v4'
FIG_DIR = SYNTHESIS_DIR / 'figures'
TAB_DIR = SYNTHESIS_DIR / 'tables'

PRIMARY_FAMILIES = ['bb84', 'bv', 'edc', 'hs', 'qrng', 'xor']
FAMILY_TITLES = {
    'bb84': 'BB84',
    'bv': 'BV',
    'edc': 'EDC',
    'hs': 'HS',
    'qrng': 'QRNG',
    'xor': 'XOR',
    'stress': 'Stress',
    'ghz': 'GHZ',
}
CALIBRATION_CASES = {
    'bb84': 'bb84_n18',
    'bv': 'bv_n18',
    'edc': 'edc_n17',
    'hs': 'hs_n18',
    'qrng': 'qrng_n18',
    'xor': 'xor_n18',
}
CALIBRATION_QUBITS = {
    'bb84': 18,
    'bv': 18,
    'edc': 17,
    'hs': 18,
    'qrng': 18,
    'xor': 18,
}

def gmean(vals: list[float]) -> float:
    pos = [v for v in vals if v > 0]
    if not pos:
        return 0.0
    return math.exp(sum(math.log(v) for v in pos) / len(pos))

def save_fig(fig: plt.Figure, base_name: str) -> None:
    svg_path = FIG_DIR / f'{base_name}.svg'
    png_path = FIG_DIR / f'{base_name}.png'
    fig.tight_layout(pad=1.2)
    fig.savefig(svg_path, metadata={'Date': None, 'Creator': 'masters-thesis-unified-v4'})
    # Normalize svg lines
    lines = [line.rstrip() for line in svg_path.read_text(encoding='utf-8').splitlines()]
    svg_path.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    fig.savefig(png_path, metadata={'Software': 'masters-thesis-unified-v4'})
    plt.close(fig)
    print(f'Saved figure: {base_name}.svg and {base_name}.png')

def make_typst_table(title: str, headers: list[str], rows: list[list[str]], note: str) -> str:
    cols_spec = '(' + ', '.join('1fr' for _ in headers) + ',)'
    lines = [
        '// Generated by thesis/synthesis/unified_v4/build.py; do not edit manually.',
        f'#text(size: 10pt, weight: "bold", {json.dumps(title, ensure_ascii=False)})',
        '#v(4pt)',
        '#{',
        '  set text(size: 8pt)',
        '  table(',
        f'    columns: {cols_spec},',
        '    inset: 4pt,',
        '    stroke: 0.35pt,',
        '    table.header(repeat: true, ' + ', '.join(f'[{h}]' for h in headers) + '),',
    ]
    for row in rows:
        cell_strs = [f'[{c}]' for c in row]
        lines.append('    ' + ', '.join(cell_strs) + ',')
    lines += [
        '  )',
        '}',
        '#v(4pt)',
        f'#text(size: 7.5pt, fill: luma(80), {json.dumps("Note: " + note, ensure_ascii=False)})',
        '',
    ]
    return '\n'.join(lines)


# -----------------------------------------------------------------------------
# Figure F1: Tasklet Speedup (2x3)
# -----------------------------------------------------------------------------
def build_figure_f1(t_rows: list[dict]) -> None:
    fig, axes = plt.subplots(2, 3, figsize=(10.5, 6.2), sharex=True, sharey=True)
    letters = ['(a)', '(b)', '(c)', '(d)', '(e)', '(f)']
    
    for idx, fam in enumerate(PRIMARY_FAMILIES):
        ax = axes[idx // 3, idx % 3]
        cid = CALIBRATION_CASES[fam]
        n_q = CALIBRATION_QUBITS[fam]
        fam_title = FAMILY_TITLES[fam]
        letter = letters[idx]
        
        rows = [r for r in t_rows if r['case_id'] == cid]
        data = {}
        for r in rows:
            t = int(r['point'].replace('T', ''))
            med = float(r['median_prepared_call_s'])
            mad = float(r['raw_mad'])
            data[t] = (med, mad)
            
        t1_med, _ = data[1]
        ts = sorted(data.keys())
        speedups = []
        low_err = []
        high_err = []
        for t in ts:
            med, mad = data[t]
            sp = t1_med / med
            sp_low = t1_med / (med + mad) if (med + mad) > 0 else sp
            sp_high = t1_med / (med - mad) if (med - mad) > 0 else sp
            speedups.append(sp)
            low_err.append(max(0.0, sp - sp_low))
            high_err.append(max(0.0, sp_high - sp))
            
        # Plot ideal scaling
        ax.plot([1, 24], [1, 24], color='#888888', linestyle=':', linewidth=1.0, label='Ideal linear ($y=T$)')
        # Plot measured
        ax.errorbar(ts, speedups, yerr=[low_err, high_err], color='#1f77b4', marker='o',
                    markersize=4, linewidth=1.4, capsize=2.5, elinewidth=0.8,
                    label='Measured speedup ($t_{\\mathrm{T1}} / t_{T}$)')
        
        ax.set_title(f'{letter} {fam_title} ($n={n_q}$)', fontweight='semibold')
        ax.set_xticks([1, 4, 8, 12, 16, 20, 24])
        ax.set_xlim(0, 25)
        ax.set_ylim(0.5, 6.0)
        ax.grid(True, linestyle='--', alpha=0.5, linewidth=0.5)
        
        if idx % 3 == 0:
            ax.set_ylabel('Speedup vs T1')
        if idx // 3 == 1:
            ax.set_xlabel('Tasklets $T$ (1 DPU)')
            
    # Add common legend in panel (a)
    axes[0, 0].legend(loc='upper left', framealpha=0.9)
    save_fig(fig, 'F1_tasklet_speedup')


# -----------------------------------------------------------------------------
# Figure F2: DPU Speedup (2x3)
# -----------------------------------------------------------------------------
def build_figure_f2(d_rows: list[dict]) -> None:
    fig, axes = plt.subplots(2, 3, figsize=(10.5, 6.2), sharex=True, sharey=True)
    letters = ['(a)', '(b)', '(c)', '(d)', '(e)', '(f)']
    
    for idx, fam in enumerate(PRIMARY_FAMILIES):
        ax = axes[idx // 3, idx % 3]
        cid = CALIBRATION_CASES[fam]
        n_q = CALIBRATION_QUBITS[fam]
        fam_title = FAMILY_TITLES[fam]
        letter = letters[idx]
        
        d_vals = [1, 2, 4, 8, 16, 32, 64]
        
        # T8
        t8_map = {int(r['point'].split('/')[0].replace('D', '')): float(r['median_prepared_call_s'])
                  for r in d_rows if r['case_id'] == cid and '/T8' in r['point']}
        t8_base = t8_map[1]
        t8_sp = [t8_base / t8_map[d] for d in d_vals]
        
        # T24
        t24_map = {int(r['point'].split('/')[0].replace('D', '')): float(r['median_prepared_call_s'])
                   for r in d_rows if r['case_id'] == cid and '/T24' in r['point']}
        t24_base = t24_map[1]
        t24_sp = [t24_base / t24_map[d] for d in d_vals]
        
        # Plot ideal scaling
        ax.plot([1, 64], [1, 64], color='#888888', linestyle=':', linewidth=1.0, label='Ideal linear ($y=D$)')
        ax.plot(d_vals, t8_sp, color='#1f77b4', marker='o', markersize=4.5, linewidth=1.4, label='T8 tasklets')
        ax.plot(d_vals, t24_sp, color='#ff7f0e', marker='s', markersize=4.5, linestyle='--', linewidth=1.4, label='T24 tasklets')
        
        ax.set_xscale('log', base=2)
        ax.set_xticks(d_vals)
        ax.set_xticklabels(['1', '2', '4', '8', '16', '32', '64'])
        ax.set_xlim(0.8, 80)
        ax.set_ylim(0.8, 3.5)
        ax.set_title(f'{letter} {fam_title} ($n={n_q}$)', fontweight='semibold')
        ax.grid(True, which='both', linestyle='--', alpha=0.5, linewidth=0.5)
        
        if idx % 3 == 0:
            ax.set_ylabel('Speedup vs D1')
        if idx // 3 == 1:
            ax.set_xlabel('DPU count $D$ (one rank)')
            
    axes[0, 0].legend(loc='upper left', framealpha=0.9)
    save_fig(fig, 'F2_dpu_speedup')


# -----------------------------------------------------------------------------
# Figure F3: Ablation Scaling (2x3)
# -----------------------------------------------------------------------------
def build_figure_f3(a_rows: list[dict]) -> None:
    fig, axes = plt.subplots(2, 3, figsize=(10.5, 6.2), sharex=True, sharey=True)
    letters = ['(a)', '(b)', '(c)', '(d)', '(e)', '(f)']
    steps = ['A0', 'A1', 'A2', 'A3', 'A4']
    step_labels = ['A0\nBase', 'A1\n+T24', 'A2\n+D4', 'A3\n+Fuse', 'A4\n+DAG']
    colors = ['#7f7f7f', '#1f77b4', '#2ca02c', '#ff7f0e', '#9467bd']
    
    for idx, fam in enumerate(PRIMARY_FAMILIES):
        ax = axes[idx // 3, idx % 3]
        cid = CALIBRATION_CASES[fam]
        n_q = CALIBRATION_QUBITS[fam]
        fam_title = FAMILY_TITLES[fam]
        letter = letters[idx]
        
        f_rows = {r['point']: (float(r['median_prepared_call_s']), float(r['raw_mad']))
                  for r in a_rows if r['case_id'] == cid}
        a0_med, _ = f_rows['A0']
        
        norm_times = [f_rows[s][0] / a0_med for s in steps]
        norm_mads = [f_rows[s][1] / a0_med for s in steps]
        
        bars = ax.bar(range(5), norm_times, yerr=norm_mads, capsize=3, color=colors,
                      edgecolor='black', linewidth=0.7, width=0.58)
        
        # Add values on top of bars
        for b_idx, (b, val) in enumerate(zip(bars, norm_times)):
            ax.text(b.get_x() + b.get_width() / 2.0, val + 0.04, f'{val:.2f}',
                    ha='center', va='bottom', fontsize=7, fontweight='medium')
            
        ax.axhline(1.0, color='#888888', linestyle='--', linewidth=0.8)
        ax.set_xticks(range(5))
        ax.set_xticklabels(step_labels)
        ax.set_ylim(0, 1.25)
        ax.set_title(f'{letter} {fam_title} ($n={n_q}$)', fontweight='semibold')
        ax.grid(True, axis='y', linestyle='--', alpha=0.5, linewidth=0.5)
        
        if idx % 3 == 0:
            ax.set_ylabel('Normalized runtime ($t / t_{\\mathrm{A0}}$)')
            
    save_fig(fig, 'F3_ablation_scaling')


# -----------------------------------------------------------------------------
# Figure F4: Quantization Tradeoff (2x3)
# -----------------------------------------------------------------------------
def build_figure_f4(q_rows: list[dict]) -> None:
    fig, axes = plt.subplots(2, 3, figsize=(10.5, 6.2), sharex=True, sharey=True)
    letters = ['(a)', '(b)', '(c)', '(d)', '(e)', '(f)']
    d_vals = [1, 2, 4, 8, 16, 32, 64]
    
    for idx, fam in enumerate(PRIMARY_FAMILIES):
        ax = axes[idx // 3, idx % 3]
        cid = CALIBRATION_CASES[fam]
        n_q = CALIBRATION_QUBITS[fam]
        fam_title = FAMILY_TITLES[fam]
        letter = letters[idx]
        
        # Cost ratio = f32_time / int8_time (> 1.0 means int8 is faster)
        ratios_t8 = []
        ratios_t24 = []
        for d in d_vals:
            f32_t8 = float(next(r['median_prepared_call_s'] for r in q_rows if r['case_id'] == cid and r['point'] == f'D{d}/T8/split_complex_float32_v1'))
            int8_t8 = float(next(r['median_prepared_call_s'] for r in q_rows if r['case_id'] == cid and r['point'] == f'D{d}/T8/complex_int8_shared_scale_v1'))
            f32_t24 = float(next(r['median_prepared_call_s'] for r in q_rows if r['case_id'] == cid and r['point'] == f'D{d}/T24/split_complex_float32_v1'))
            int8_t24 = float(next(r['median_prepared_call_s'] for r in q_rows if r['case_id'] == cid and r['point'] == f'D{d}/T24/complex_int8_shared_scale_v1'))
            ratios_t8.append(f32_t8 / int8_t8)
            ratios_t24.append(f32_t24 / int8_t24)
            
        ax.axhline(1.0, color='#d62728', linestyle='--', linewidth=0.9, label='Parity ($t_{\\mathrm{f32}} = t_{\\mathrm{int8}}$)')
        ax.plot(d_vals, ratios_t8, color='#2ca02c', marker='^', markersize=5, linewidth=1.4, label='T8 tasklets')
        ax.plot(d_vals, ratios_t24, color='#9467bd', marker='v', markersize=5, linestyle='--', linewidth=1.4, label='T24 tasklets')
        
        ax.set_xscale('log', base=2)
        ax.set_xticks(d_vals)
        ax.set_xticklabels(['1', '2', '4', '8', '16', '32', '64'])
        ax.set_xlim(0.8, 80)
        ax.set_ylim(0.8, 2.30)
        ax.set_title(f'{letter} {fam_title} ($n={n_q}$)', fontweight='semibold')
        ax.grid(True, which='both', linestyle='--', alpha=0.5, linewidth=0.5)
        
        if idx % 3 == 0:
            ax.set_ylabel('Cost ratio ($t_{\\mathrm{f32}} / t_{\\mathrm{int8}}$)')
        if idx // 3 == 1:
            ax.set_xlabel('DPU count $D$ (matched topology)')
            
    axes[0, 0].legend(loc='upper right', framealpha=0.9)
    save_fig(fig, 'F4_quantization_tradeoff')


# -----------------------------------------------------------------------------
# Figure F5: Original P6 Forest Plot (2x2)
# -----------------------------------------------------------------------------
def build_figure_f5() -> None:
    p6_agg_path = REPO_ROOT / 'thesis' / 'synthesis' / 'generated' / 'data' / 'p6_aggregates.csv'
    p6_cell_path = REPO_ROOT / 'thesis' / 'synthesis' / 'generated' / 'data' / 'p6_cells.csv'
    
    with open(p6_agg_path) as f:
        p6_aggs = list(csv.DictReader(f))
    with open(p6_cell_path) as f:
        p6_cells = list(csv.DictReader(f))
        
    contrasts = [
        ('G/F', 'Greedy vs FLOP selection', '(a)'),
        ('F/R', 'FLOP selection vs Reranking', '(b)'),
        ('R/U', 'Reranking vs Guided search', '(c)'),
        ('G/U', 'Greedy vs Guided search', '(d)'),
    ]
    
    fig, axes = plt.subplots(2, 2, figsize=(10.5, 7.2))
    
    for idx, (cnt, desc, letter) in enumerate(contrasts):
        ax = axes[idx // 2, idx % 2]
        
        # Items to display vertically:
        # 1. Overall (all 12 cells)
        # 2. 1 DPU / T8 (6 cells)
        # 3. 4 DPU / T8 (6 cells)
        # 4..9: 6 primary families (1 DPU / T8 and 4 DPU / T8 individual cells)
        rows_to_plot = []
        
        # Aggregates
        for grp, grp_label in [('all', 'Overall (All 12 cells)'),
                               ('1dpu_t8', 'Topology: 1 DPU / T8 (6 cells)'),
                               ('4dpu_t8', 'Topology: 4 DPU / T8 (6 cells)')]:
            match = next((r for r in p6_aggs if r['group'] == grp and r['contrast'] == cnt and r['metric'] == 'session_inclusive_s'), None)
            if match:
                rows_to_plot.append({
                    'label': grp_label,
                    'ratio': float(match['ratio']),
                    'low': float(match['paired_bootstrap_low']),
                    'high': float(match['paired_bootstrap_high']),
                    'is_agg': True,
                    'group': grp,
                })
                
        # Per-cell items
        cells_for_cnt = [r for r in p6_cells if r['contrast'] == cnt and r['metric'] == 'session_inclusive_s']
        # Sort cells deterministically
        cells_for_cnt.sort(key=lambda c: (c['family'], c['topology_id']))
        for c in cells_for_cnt:
            fam_name = c['family']
            topo = c['topology_id'].replace('_', ' ').upper()
            rows_to_plot.append({
                'label': f'{fam_name} ({topo})',
                'ratio': float(c['ratio']),
                'low': float(c['paired_bootstrap_low']),
                'high': float(c['paired_bootstrap_high']),
                'is_agg': False,
                'group': c['topology_id'],
            })
            
        y_pos = list(range(len(rows_to_plot)))
        y_pos.reverse()  # Top to bottom
        
        ax.axvline(1.0, color='#888888', linestyle='--', linewidth=0.9)
        
        for y, r in zip(y_pos, rows_to_plot):
            ratio = r['ratio']
            low = r['low']
            high = r['high']
            
            if r['is_agg']:
                color = '#d62728' if r['group'] == 'all' else ('#1f77b4' if r['group'] == '1dpu_t8' else '#ff7f0e')
                ax.errorbar([ratio], [y], xerr=[[ratio - low], [high - ratio]],
                            fmt='D', markersize=6.5, color=color, capsize=3.5, elinewidth=1.6, zorder=4)
            else:
                color = '#2ca02c' if '1DPU' in r['label'] else '#9467bd'
                ax.errorbar([ratio], [y], xerr=[[max(0, ratio - low)], [max(0, high - ratio)]],
                            fmt='o', markersize=4, color=color, capsize=2, elinewidth=0.8, alpha=0.85, zorder=3)
                
        ax.set_yticks(y_pos)
        ax.set_yticklabels([r['label'] for r in rows_to_plot], fontsize=7.5)
        ax.set_title(f'{letter} Contrast {cnt}: {desc}', fontweight='semibold')
        ax.set_xlabel('Execution time ratio (baseline / alternative)')
        ax.grid(True, axis='x', linestyle='--', alpha=0.5, linewidth=0.5)
        
    save_fig(fig, 'F5_p6_transfer')


# -----------------------------------------------------------------------------
# Figure F6: LAST Comparison All-Family Width Curves (2x3)
# -----------------------------------------------------------------------------
def build_figure_f6(w_rows: list[dict]) -> None:
    fig, axes = plt.subplots(2, 3, figsize=(10.5, 6.2), sharex=False, sharey=True)
    letters = ['(a)', '(b)', '(c)', '(d)', '(e)', '(f)']
    
    for idx, fam in enumerate(PRIMARY_FAMILIES):
        ax = axes[idx // 3, idx % 3]
        fam_title = FAMILY_TITLES[fam]
        letter = letters[idx]
        
        rows = [r for r in w_rows if r['case_id'].startswith(f'{fam}_n')]
        
        # Parse n from case_id
        # Role data: n -> time
        f32_data = {}
        int8_data = {}
        p8_data = {}
        p1_data = {}
        
        for r in rows:
            n = int(r['case_id'].split('_n')[1])
            t = float(r['median_job_to_state_cached_path_s'])
            role = r['role']
            if role == 'upmem_f32':
                f32_data[n] = t
            elif role == 'upmem_int8':
                int8_data[n] = t
            elif role == 'quest32_p8':
                p8_data[n] = t
            elif role == 'quest32_p1':
                p1_data[n] = t
                
        # Sorted x coordinates
        all_ns = sorted(set(list(f32_data.keys()) + list(p8_data.keys())))
        
        # Plot curves
        ns_p8 = sorted(p8_data.keys())
        ax.plot(ns_p8, [p8_data[n] for n in ns_p8], color='#9467bd', marker='D',
                markersize=4, linestyle='-.', linewidth=1.3, label='QuEST CPU (P8, 8 threads)')
        
        ns_p1 = sorted(p1_data.keys())
        ax.plot(ns_p1, [p1_data[n] for n in ns_p1], color='#7f7f7f', marker='^',
                markersize=3.5, linestyle=':', linewidth=1.1, label='QuEST CPU (P1, 1 thread)')
        
        ns_f32 = sorted(f32_data.keys())
        ax.plot(ns_f32, [f32_data[n] for n in ns_f32], color='#1f77b4', marker='o',
                markersize=4.5, linewidth=1.4, label='UPMEM float32 (selected)')
        
        ns_int8 = sorted(int8_data.keys())
        ax.plot(ns_int8, [int8_data[n] for n in ns_int8], color='#2ca02c', marker='s',
                markersize=4.5, linestyle='--', linewidth=1.4, label='UPMEM int8 (selected)')
        
        # Unsupported point at highest n (e.g. n=26 or n=25)
        max_n = max(all_ns)
        if max_n not in f32_data:
            # Mark unsupported boundary explicitly (never zero runtime)
            ax.plot([max_n], [40.0], marker='x', markersize=7, color='#d62728', markeredgewidth=1.8)
            ax.text(max_n, 48.0, 'MRAM\nlimit', color='#d62728', fontsize=6.5, ha='center', va='bottom', fontweight='bold')
            
        ax.set_yscale('log')
        ax.set_xticks(all_ns)
        ax.set_ylim(1e-4, 3e2)
        ax.set_title(f'{letter} {fam_title}', fontweight='semibold')
        ax.grid(True, which='both', linestyle='--', alpha=0.5, linewidth=0.5)
        
        if idx % 3 == 0:
            ax.set_ylabel('Cached-path job-to-state time (s)')
        if idx // 3 == 1:
            ax.set_xlabel('Circuit width $n$ (qubits)')
            
    axes[0, 0].legend(loc='upper left', framealpha=0.9, fontsize=6.8)
    save_fig(fig, 'F6_final_comparison')


# -----------------------------------------------------------------------------
# Typst Table T1: Tasklet Speedup
# -----------------------------------------------------------------------------
def build_table_t1(t_rows: list[dict]) -> None:
    headers = ['Tasklets', 'BB84', 'BV', 'EDC', 'HS', 'QRNG', 'XOR', 'GeoMean']
    rows = []
    
    # Grid of tasklet counts
    for t in range(1, 25):
        row = [f'T{t}']
        sps = []
        for fam in PRIMARY_FAMILIES:
            cid = CALIBRATION_CASES[fam]
            t_map = {int(r['point'].replace('T', '')): float(r['median_prepared_call_s'])
                     for r in t_rows if r['case_id'] == cid}
            sp = t_map[1] / t_map[t]
            sps.append(sp)
            row.append(f'{sp:.2f}×')
        gm = gmean(sps)
        row.append(f'*{gm:.2f}×*')
        rows.append(row)
        
    note = (
        'Measured prepared-call median execution time ratios relative to single-tasklet baseline (T1) on 1 physical DPU. '
        'Fixed circuit widths: n=18 (BB84, BV, HS, QRNG, XOR) and n=17 (EDC). Equal-family geometric mean across all six primary families. '
        'Five measured blocks per cell.'
    )
    content = make_typst_table('Primary-Family Tasklet Scaling (1 DPU, T1..T24)', headers, rows, note)
    (TAB_DIR / 'T1_tasklet_speedup.typ').write_text(content, encoding='utf-8')
    print('Saved table: T1_tasklet_speedup.typ')


# -----------------------------------------------------------------------------
# Typst Table T2: DPU Speedup
# -----------------------------------------------------------------------------
def build_table_t2(d_rows: list[dict]) -> None:
    headers = ['DPUs', 'Tasklets', 'BB84', 'BV', 'EDC', 'HS', 'QRNG', 'XOR', 'GeoMean']
    rows = []
    
    for t_val in [8, 24]:
        for d in [1, 2, 4, 8, 16, 32, 64]:
            row = [f'D{d}', f'T{t_val}']
            sps = []
            for fam in PRIMARY_FAMILIES:
                cid = CALIBRATION_CASES[fam]
                d_map = {int(r['point'].split('/')[0].replace('D', '')): float(r['median_prepared_call_s'])
                         for r in d_rows if r['case_id'] == cid and f'/T{t_val}' in r['point']}
                sp = d_map[1] / d_map[d]
                sps.append(sp)
                row.append(f'{sp:.2f}×')
            gm = gmean(sps)
            row.append(f'*{gm:.2f}×*')
            rows.append(row)
            
    note = (
        'Measured prepared-call median execution time ratios relative to single-DPU baseline (D1) at matched tasklet count (T8 or T24). '
        'One physical rank (up to 64 DPUs). Equal-family geometric mean across all six primary families. '
        'Five measured blocks per cell.'
    )
    content = make_typst_table('Primary-Family DPU Scaling (1 Rank, D1..D64)', headers, rows, note)
    (TAB_DIR / 'T2_dpu_speedup.typ').write_text(content, encoding='utf-8')
    print('Saved table: T2_dpu_speedup.typ')


# -----------------------------------------------------------------------------
# Typst Table T3: Cumulative Ablation
# -----------------------------------------------------------------------------
def build_table_t3(a_rows: list[dict], agg_rows: list[dict]) -> None:
    headers = ['Stage', 'Architecture / Optimization', 'Incremental Ratio', 'Cumulative vs A0', 'Time Reduction', 'GeoMean Speedup']
    
    stage_meta = [
        ('A0', '1 DPU, 1 tasklet, serial, unfused', '1.00×', '1.00×', '0.0%', '1.00×'),
        ('A1', '1 DPU, 24 tasklets, serial, unfused (Tasklet parallelism)', '', '', '', ''),
        ('A2', '4 DPUs, 8 tasklets, serial, unfused (Multi-DPU scaling)', '', '', '', ''),
        ('A3', '4 DPUs, 8 tasklets, serial, fused (Gate fusion)', '', '', '', ''),
        ('A4', '4 DPUs, 8 tasklets, static DAG waves, fused (DAG scheduling)', '', '', '', ''),
    ]
    
    # Calculate geometric means across the 6 primary families
    steps = ['A0', 'A1', 'A2', 'A3', 'A4']
    cum_by_step = {s: [] for s in steps}
    inc_by_step = {'A1': [], 'A2': [], 'A3': [], 'A4': []}
    
    for fam in PRIMARY_FAMILIES:
        cid = CALIBRATION_CASES[fam]
        f_rows = {r['point']: float(r['median_prepared_call_s']) for r in a_rows if r['case_id'] == cid}
        a0 = f_rows['A0']
        for s in steps:
            cum_by_step[s].append(a0 / f_rows[s])
        inc_by_step['A1'].append(f_rows['A0'] / f_rows['A1'])
        inc_by_step['A2'].append(f_rows['A1'] / f_rows['A2'])
        inc_by_step['A3'].append(f_rows['A2'] / f_rows['A3'])
        inc_by_step['A4'].append(f_rows['A3'] / f_rows['A4'])
        
    rows = []
    for idx, s in enumerate(steps):
        name, desc, _, _, _, _ = stage_meta[idx]
        cum_gm = gmean(cum_by_step[s])
        time_red = 100.0 * (1.0 - 1.0 / cum_gm)
        if s == 'A0':
            inc_str = '—'
        else:
            inc_gm = gmean(inc_by_step[s])
            inc_str = f'{inc_gm:.2f}×'
        rows.append([name, desc, inc_str, f'{cum_gm:.2f}×', f'{time_red:.1f}%', f'*{cum_gm:.2f}×*'])
        
    note = (
        'Seven measured blocks. Incremental ratios reflect step-to-step geometric mean speedup across six primary families. '
        'Cumulative ratio is speedup relative to baseline A0. Time reduction is calculated as 100(1 - 1/ratio). '
        'All stages evaluate greedy contraction paths with WRAM panels and packed waves.'
    )
    content = make_typst_table('Cumulative Architectural and Optimization Ablation (A0..A4)', headers, rows, note)
    (TAB_DIR / 'T3_ablation_cumulative.typ').write_text(content, encoding='utf-8')
    print('Saved table: T3_ablation_cumulative.typ')


# -----------------------------------------------------------------------------
# Typst Table T4: Quantization Error and Cost Tradeoff
# -----------------------------------------------------------------------------
def build_table_t4(q_rows: list[dict], obs_rows: list[dict]) -> None:
    headers = ['Family', 'Qubits ($n$)', 'Matched (D, T)', 'Float32 (s)', 'Int8 (s)', 'Speedup (f32/int8)', 'Max Rel L2 Error', 'Min Fidelity']
    
    # Pick matched D=4, T=24 as representative
    fams = PRIMARY_FAMILIES + ['stress']
    cases = [CALIBRATION_CASES[f] if f in CALIBRATION_CASES else 'stress_n16_l2' for f in fams]
    
    rows = []
    for fam, cid in zip(fams, cases):
        fam_name = FAMILY_TITLES[fam]
        n_val = 16 if 'stress' in fam else CALIBRATION_QUBITS[fam]
        
        # Float32 and Int8 times at D4/T24
        f32_t = float(next(r['median_prepared_call_s'] for r in q_rows if r['case_id'] == cid and r['point'] == 'D4/T24/split_complex_float32_v1'))
        int8_t = float(next(r['median_prepared_call_s'] for r in q_rows if r['case_id'] == cid and r['point'] == 'D4/T24/complex_int8_shared_scale_v1'))
        sp = f32_t / int8_t
        
        # Accuracy metrics from observations
        int8_slots = [r for r in obs_rows if r['case_id'] == cid and 'int8' in r.get('arm', '') and not (r.get('warmup') == 'True' or r.get('warmup') is True)]
        l2_errs = []
        fids = []
        for s in int8_slots:
            val_str = s.get('validation')
            if not val_str or val_str == 'None':
                continue
            try:
                v = json.loads(val_str)
            except Exception:
                try:
                    v = ast.literal_eval(val_str)
                except Exception:
                    continue
            if 'relative_l2' in v:
                l2_errs.append(v['relative_l2'])
            if 'fidelity_normalized' in v:
                fids.append(v['fidelity_normalized'])
                
        max_l2 = f'{max(l2_errs):.2e}' if l2_errs else '—'
        min_fid = f'{min(fids):.6f}' if fids else '—'
        
        rows.append([fam_name, str(n_val), 'D4 / T24', f'{f32_t:.4f}s', f'{int8_t:.4f}s', f'{sp:.2f}×', max_l2, min_fid])
        
    note = (
        'Physical execution on UPMEM hardware at matched topology (4 DPUs, 24 tasklets, static DAG waves). '
        'Speedup > 1.0 indicates int8 runtime advantage. Errors computed against analytic complex128 reference statevectors. '
        'All primary families retain state fidelity > 0.99999.'
    )
    content = make_typst_table('Quantization Trade-Off: Execution Speedup and Numerical Accuracy', headers, rows, note)
    (TAB_DIR / 'T4_quantization_error_cost.typ').write_text(content, encoding='utf-8')
    print('Saved table: T4_quantization_error_cost.typ')


# -----------------------------------------------------------------------------
# Typst Table T5: Selection Winners
# -----------------------------------------------------------------------------
def build_table_t5(selection_data: dict) -> None:
    headers = ['Family', 'Precision Policy', 'Selected DPUs', 'Selected Tasklets', 'Median Prepared Call (s)', 'Cell Identifier']
    rows = []
    
    for item in selection_data.get('selections', []):
        fam = FAMILY_TITLES.get(item['family'], item['family'])
        policy = 'Float32' if 'float32' in item['policy'] else 'Int8'
        sel = item['selected']
        dpus = f'D{sel["dpus"]}'
        tasklets = f'T{sel["tasklets"]}'
        time_s = f'{sel["median_prepared_call_s"]:.4f}s'
        cell_short = sel['cell_id'][:18] + '...'
        rows.append([fam, policy, dpus, tasklets, time_s, cell_short])
        
    note = (
        'Selection rule: minimum median prepared-call time across calibration blocks 1..5, breaking ties by smaller DPU count '
        'then smaller tasklet count. 12 primary winners + 2 supplementary Stress policy selections. '
        'Quality-unqualified int8 candidates are barred from selection. Selections frozen before final comparison phase.'
    )
    content = make_typst_table('Calibrated Topology Selection Winners (Phase C)', headers, rows, note)
    (TAB_DIR / 'T5_selection_winners.typ').write_text(content, encoding='utf-8')
    print('Saved table: T5_selection_winners.typ')


# -----------------------------------------------------------------------------
# Typst Table T6: Cold and Amortized Costs
# -----------------------------------------------------------------------------
def build_table_t6(cold_rows: list[dict]) -> None:
    headers = ['Workload', 'Qubits ($n$)', 'Cold Planning (s)', 'Steady Prepared (s)', 'Amortized $k=1$ (s)', 'Amortized $k=10$ (s)', 'Amortized $k=100$ (s)']
    rows = []
    
    # Pick calibration cases and selected widths
    target_cids = [
        'bb84_n08', 'bb84_n18', 'bb84_n24',
        'bv_n08', 'bv_n18', 'bv_n24',
        'edc_n07', 'edc_n17', 'edc_n23',
        'hs_n08', 'hs_n18', 'hs_n24',
        'qrng_n08', 'qrng_n18', 'qrng_n24',
        'xor_n08', 'xor_n18', 'xor_n24',
    ]
    
    for cid in target_cids:
        match = next((r for r in cold_rows if r['case_id'] == cid), None)
        if not match:
            continue
        fam = FAMILY_TITLES.get(match['family'], match['family'])
        n_val = match['n']
        plan_s = float(match['planning_once_s'])
        exec_s = float(match['median_cached_s'])
        k1 = float(match['amortized_k1'])
        k10 = float(match['amortized_k10'])
        k100 = float(match['amortized_k100'])
        rows.append([f'{fam} ($n={n_val}$)', str(n_val), f'{plan_s:.2f}s', f'{exec_s:.3f}s', f'{k1:.2f}s', f'{k10:.2f}s', f'{k100:.3f}s'])
        
    note = (
        'Cold planning time reflects single-shot offline greedy contraction path search. '
        'Steady execution reflects cached-path prepared-call time on physical UPMEM DPUs. '
        'Amortized cost per execution is computed as (T_plan + k * T_exec) / k across repeated invocations.'
    )
    content = make_typst_table('Cold-Start Planning Overhead and Amortized Execution Costs', headers, rows, note)
    (TAB_DIR / 'T6_cold_amortized_costs.typ').write_text(content, encoding='utf-8')
    print('Saved table: T6_cold_amortized_costs.typ')


# -----------------------------------------------------------------------------
# Typst Table T7: Campaign Accounting
# -----------------------------------------------------------------------------
def build_table_t7() -> None:
    headers = ['Evaluation Phase / Suite', 'Planned Cells', 'Planned Slots', 'Issued Slots', 'Successful', 'Unsupported', 'Dedup Avoided']
    rows = [
        ['Physical UPMEM Qualification', '18', '108', '108', '108', '0', '0'],
        ['QuEST CPU Qualification', '32', '32', '32', '32', '0', '0'],
        ['Simulation Qualification', '18', '108', '108', '108', '0', '0'],
        ['R-Path Qualification (Tiny)', '4', '4', '4', '4', '0', '0'],
        ['Calibration Phase C (Blocks 0..7)', '434', '2,674', '2,674', '2,674', '0', '714'],
        ['Topology Selection (Phase C)', '14 winners', '—', '—', '14', '0', '—'],
        ['Shared R-Path Search (52 cases × 128)', '52', '6,656 searches', '6,656', '6,656', '0', '—'],
        ['Final Comparison Phase W & S (Blocks 0..5)', '260', '1,560', '1,452', '1,452', '108', '0'],
        ['Total Physical UPMEM Campaign', '—', '—', '3,306', '3,306', '108', '714'],
    ]
    note = (
        'All planned slots are fully accounted for. Physical slot executions totaled 3,306, strictly below the <= 3,406 physical slot limit. '
        '108 final slots were not issued due to verified int8 DPU/MRAM capacity boundaries. '
        'Zero unresolved slots. Dual archives A and B verified byte-identical across all 8,279 retained files.'
    )
    content = make_typst_table('Unified Evaluation Campaign Accounting and Verification', headers, rows, note)
    (TAB_DIR / 'T7_campaign_accounting.typ').write_text(content, encoding='utf-8')
    print('Saved table: T7_campaign_accounting.typ')


# -----------------------------------------------------------------------------
# README and Checksum Generation
# -----------------------------------------------------------------------------
def build_readme() -> None:
    readme_content = """# Unified Final Evaluation v4 — Publication Synthesis

This directory contains deterministic publication figures and self-contained Typst tables for the Master's thesis.

All figures and tables read exclusively from canonical published evaluation results in:
`thesis/implementation/thesis_results/unified_final_v4/`

## Figure Inventory

| Figure | SVG | PNG | Description |
|---|---|---|---|
| **F1** | `figures/F1_tasklet_speedup.svg` | `figures/F1_tasklet_speedup.png` | 2×3 primary-family tasklet speedup (T1..T24) on 1 DPU, with ideal linear scaling and error bars. |
| **F2** | `figures/F2_dpu_speedup.svg` | `figures/F2_dpu_speedup.png` | 2×3 primary-family DPU speedup across D1..D64 at T8 and T24, showing scaling saturation beyond 16 DPUs. |
| **F3** | `figures/F3_ablation_scaling.svg` | `figures/F3_ablation_scaling.png` | 2×3 normalized runtime across cumulative stages A0..A4 (Base -> Tasklets -> DPUs -> Fusion -> DAG). |
| **F4** | `figures/F4_quantization_tradeoff.svg` | `figures/F4_quantization_tradeoff.png` | 2×3 physical quantization execution-cost ratios ($t_{\\mathrm{f32}} / t_{\\mathrm{int8}}$) at matched topology. |
| **F5** | `figures/F5_p6_transfer.svg` | `figures/F5_p6_transfer.png` | 2×2 forest plot of original P6 contrasts (G/F, F/R, R/U, G/U) with paired bootstrap intervals. |
| **F6** | `figures/F6_final_comparison.svg` | `figures/F6_final_comparison.png` | 2×3 LAST comparison width curves: selected UPMEM f32, UPMEM int8, QuEST CPU P8 and P1, with MRAM limit marker. |

## Table Inventory

| Table | File | Description |
|---|---|---|
| **T1** | `tables/T1_tasklet_speedup.typ` | Tasklet scaling (T1..T24) per primary family and geometric mean speedup. |
| **T2** | `tables/T2_dpu_speedup.typ` | DPU scaling (D1..D64) for T8 and T24 series per primary family and geometric mean. |
| **T3** | `tables/T3_ablation_cumulative.typ` | Cumulative architectural and optimization ablation (A0..A4) speedup and time reduction. |
| **T4** | `tables/T4_quantization_error_cost.typ` | Quantization execution speedup and numerical accuracy disclosure (relative L2, fidelity). |
| **T5** | `tables/T5_selection_winners.typ` | Deterministic topology selection winners (12 primary + 2 supplementary Stress). |
| **T6** | `tables/T6_cold_amortized_costs.typ` | Cold-start planning overhead versus steady execution times and amortized costs ($k=1, 10, 100$). |
| **T7** | `tables/T7_campaign_accounting.typ` | Complete campaign execution accounting, slot reconciliation, and archive verification. |

## Verification

To regenerate all figures, tables, and verify checksums:
```bash
python3 thesis/synthesis/unified_v4/build.py
sha256sum -c thesis/synthesis/unified_v4/SHA256SUMS
```
"""
    (SYNTHESIS_DIR / 'README.md').write_text(readme_content, encoding='utf-8')
    print('Saved README.md')

def build_checksums() -> None:
    lines = []
    files_to_hash = []
    
    # Figures
    for ext in ['*.svg', '*.png']:
        for p in sorted(FIG_DIR.glob(ext)):
            files_to_hash.append(p)
            
    # Tables
    for p in sorted(TAB_DIR.glob('*.typ')):
        files_to_hash.append(p)
        
    # README
    readme_path = SYNTHESIS_DIR / 'README.md'
    if readme_path.exists():
        files_to_hash.append(readme_path)
        
    for p in files_to_hash:
        rel = p.relative_to(SYNTHESIS_DIR)
        digest = hashlib.sha256(p.read_bytes()).hexdigest()
        lines.append(f'{digest}  {rel}')
        
    checksum_file = SYNTHESIS_DIR / 'SHA256SUMS'
    checksum_file.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'Saved SHA256SUMS with {len(lines)} files')


# -----------------------------------------------------------------------------
# Main Runner
# -----------------------------------------------------------------------------
def main() -> None:
    print('=== Unified Evaluation v4 Publication Synthesis Build ===')
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    TAB_DIR.mkdir(parents=True, exist_ok=True)
    
    # Load canonical readout files
    with open(CANONICAL_DIR / 'readout' / 'T.csv') as f:
        t_rows = list(csv.DictReader(f))
    with open(CANONICAL_DIR / 'readout' / 'D.csv') as f:
        d_rows = list(csv.DictReader(f))
    with open(CANONICAL_DIR / 'readout' / 'A.csv') as f:
        a_rows = list(csv.DictReader(f))
    with open(CANONICAL_DIR / 'readout' / 'Q.csv') as f:
        q_rows = list(csv.DictReader(f))
    with open(CANONICAL_DIR / 'readout' / 'W.csv') as f:
        w_rows = list(csv.DictReader(f))
    with open(CANONICAL_DIR / 'readout' / 'aggregates.csv') as f:
        agg_rows = list(csv.DictReader(f))
    with open(CANONICAL_DIR / 'readout' / 'cold_cost.csv') as f:
        cold_rows = list(csv.DictReader(f))
    with open(CANONICAL_DIR / 'readout' / 'observations.csv') as f:
        obs_rows = list(csv.DictReader(f))
    with open(CANONICAL_DIR / 'selection.json') as f:
        selection_data = json.load(f)
        
    # Build figures F1..F6
    print('Generating figures F1..F6...')
    build_figure_f1(t_rows)
    build_figure_f2(d_rows)
    build_figure_f3(a_rows)
    build_figure_f4(q_rows)
    build_figure_f5()
    build_figure_f6(w_rows)
    
    # Build tables T1..T7
    print('Generating Typst tables T1..T7...')
    build_table_t1(t_rows)
    build_table_t2(d_rows)
    build_table_t3(a_rows, agg_rows)
    build_table_t4(q_rows, obs_rows)
    build_table_t5(selection_data)
    build_table_t6(cold_rows)
    build_table_t7()
    
    # Build README and checksums
    print('Generating README and SHA256SUMS...')
    build_readme()
    build_checksums()
    print('=== Synthesis Build Complete! ===')

if __name__ == '__main__':
    main()
