// Generated by thesis/synthesis/unified_v4/build.py; do not edit manually.
#text(size: 10pt, weight: "bold", "Primary-Family DPU Scaling (1 Rank, D1..D64)")
#v(4pt)
#{
  set text(size: 8pt)
  table(
    columns: (1fr, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr,),
    inset: 4pt,
    stroke: 0.35pt,
    table.header(repeat: true, [DPUs], [Tasklets], [BB84], [BV], [EDC], [HS], [QRNG], [XOR], [GeoMean]),
    [D1], [T8], [1.00×], [1.00×], [1.00×], [1.00×], [1.00×], [1.00×], [*1.00×*],
    [D2], [T8], [1.30×], [1.24×], [1.20×], [1.20×], [1.41×], [1.33×], [*1.28×*],
    [D4], [T8], [1.61×], [1.51×], [1.66×], [1.35×], [1.73×], [1.66×], [*1.58×*],
    [D8], [T8], [1.60×], [1.49×], [2.36×], [1.35×], [1.72×], [2.13×], [*1.74×*],
    [D16], [T8], [1.51×], [1.38×], [2.73×], [1.31×], [1.66×], [2.40×], [*1.76×*],
    [D32], [T8], [1.29×], [1.19×], [2.53×], [1.22×], [1.43×], [2.28×], [*1.58×*],
    [D64], [T8], [1.10×], [0.99×], [2.32×], [1.11×], [1.22×], [2.13×], [*1.39×*],
    [D1], [T24], [1.00×], [1.00×], [1.00×], [1.00×], [1.00×], [1.00×], [*1.00×*],
    [D2], [T24], [1.25×], [1.24×], [1.21×], [1.22×], [1.35×], [1.29×], [*1.26×*],
    [D4], [T24], [1.47×], [1.42×], [1.66×], [1.34×], [1.65×], [1.65×], [*1.53×*],
    [D8], [T24], [1.42×], [1.43×], [2.44×], [1.31×], [1.62×], [2.18×], [*1.69×*],
    [D16], [T24], [1.36×], [1.32×], [2.77×], [1.31×], [1.58×], [2.46×], [*1.72×*],
    [D32], [T24], [1.17×], [1.12×], [2.65×], [1.22×], [1.37×], [2.35×], [*1.54×*],
    [D64], [T24], [0.98×], [0.94×], [2.38×], [1.10×], [1.15×], [2.22×], [*1.35×*],
  )
}
#v(4pt)
#text(size: 7.5pt, fill: luma(80), "Note: Measured prepared-call median execution time ratios relative to single-DPU baseline (D1) at matched tasklet count (T8 or T24). One physical rank (up to 64 DPUs). Equal-family geometric mean across all six primary families. Five measured blocks per cell.")
