// Generated by thesis/synthesis/unified_v4/build.py; do not edit manually.
#text(size: 10pt, weight: "bold", "Cumulative Architectural and Optimization Ablation (A0..A4)")
#v(4pt)
#{
  set text(size: 8pt)
  table(
    columns: (1fr, 1fr, 1fr, 1fr, 1fr, 1fr,),
    inset: 4pt,
    stroke: 0.35pt,
    table.header(repeat: true, [Stage], [Architecture / Optimization], [Incremental Ratio], [Cumulative vs A0], [Time Reduction], [GeoMean Speedup]),
    [A0], [D1/T1 serial unfused], [—], [1.00×], [0.0%], [*1.00×*],
    [A1], [D1/T8 serial unfused], [2.99×], [2.99×], [66.5%], [*2.99×*],
    [A2], [D4/T8 serial unfused], [1.21×], [3.62×], [72.3%], [*3.62×*],
    [A3], [D4/T8 serial fused (complex launch fusion / four-product fusion)], [1.69×], [6.10×], [83.6%], [*6.10×*],
    [A4], [D4/T8 static-DAG fused (complex launch fusion / four-product fusion)], [1.02×], [6.25×], [84.0%], [*6.25×*],
  )
}
#v(4pt)
#text(size: 7.5pt, fill: luma(80), "Note: Seven measured blocks. Incremental ratios reflect step-to-step geometric mean speedup across six primary families. Cumulative ratio is speedup relative to baseline A0. Time reduction is calculated as 100(1 - 1/ratio). All stages evaluate greedy contraction paths with WRAM panels and packed waves.")
