// Generated by thesis/synthesis/unified_v4/build.py; do not edit manually.
#text(size: 10pt, weight: "bold", "Quantization Trade-Off: Execution Speedup and Numerical Accuracy")
#v(4pt)
#{
  set text(size: 8pt)
  table(
    columns: (1fr, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr,),
    inset: 4pt,
    stroke: 0.35pt,
    table.header(repeat: true, [Family], [Qubits ($n$)], [Matched (D, T)], [Float32 (s)], [Int8 (s)], [Speedup (f32/int8)], [Max Rel L2 Error], [Min Fidelity]),
    [BB84], [18], [D4 / T24], [0.4213s], [0.4029s], [1.05×], [2.98e-07], [1.000000],
    [BV], [18], [D4 / T24], [0.5680s], [0.5650s], [1.01×], [1.01e-07], [1.000000],
    [EDC], [17], [D4 / T24], [1.9074s], [1.2062s], [1.58×], [2.21e-03], [0.999996],
    [HS], [18], [D4 / T24], [1.0357s], [1.0525s], [0.98×], [1.07e-06], [1.000000],
    [QRNG], [18], [D4 / T24], [0.4593s], [0.3973s], [1.16×], [5.36e-07], [1.000000],
    [XOR], [18], [D4 / T24], [1.9461s], [1.4349s], [1.36×], [6.91e-07], [1.000000],
    [Stress], [16], [D4 / T24], [1.1184s], [0.8951s], [1.25×], [5.84e-02], [0.996762],
  )
}
#v(4pt)
#text(size: 7.5pt, fill: luma(80), "Note: Physical execution on UPMEM hardware at matched topology (4 DPUs, 24 tasklets, static DAG waves). Speedup > 1.0 indicates int8 runtime advantage. Errors computed against analytic complex128 reference statevectors. All primary families retain state fidelity > 0.99999.")
