// Generated by thesis/synthesis/unified_v4/build.py; do not edit manually.
#text(size: 10pt, weight: "bold", "Calibrated Topology Selection Winners (Phase C)")
#v(4pt)
#{
  set text(size: 8pt)
  table(
    columns: (1fr, 1fr, 1fr, 1fr, 1fr, 1fr,),
    inset: 4pt,
    stroke: 0.35pt,
    table.header(repeat: true, [Family], [Precision Policy], [Selected DPUs], [Selected Tasklets], [Median Prepared Call (s)], [Cell Identifier]),
    [BB84], [Float32], [D4], [T24], [0.4213s], [cell-c6b638591bd34...],
    [BB84], [Int8], [D4], [T8], [0.3970s], [cell-8ad890c8af325...],
    [BV], [Float32], [D8], [T24], [0.5675s], [cell-c55ecad90eac6...],
    [BV], [Int8], [D4], [T8], [0.5410s], [cell-881e081ecb154...],
    [EDC], [Float32], [D16], [T8], [1.1325s], [cell-20f030b1d877b...],
    [EDC], [Int8], [D16], [T8], [0.8816s], [cell-33f4ec0abfd29...],
    [HS], [Float32], [D4], [T24], [1.0357s], [cell-ca877e196041c...],
    [HS], [Int8], [D8], [T8], [1.0313s], [cell-bf008e921538d...],
    [QRNG], [Float32], [D4], [T24], [0.4593s], [cell-5690d57216e38...],
    [QRNG], [Int8], [D4], [T24], [0.3973s], [cell-ca15984a0a023...],
    [XOR], [Float32], [D16], [T8], [1.2830s], [cell-7a3fdf41530e9...],
    [XOR], [Int8], [D16], [T8], [1.1113s], [cell-984e1a7ae27c8...],
    [Stress], [Float32], [D16], [T24], [0.9527s], [cell-e829c9ee9dc61...],
    [Stress], [Int8], [D16], [T24], [0.8637s], [cell-ad8b8d8aa10a0...],
  )
}
#v(4pt)
#text(size: 7.5pt, fill: luma(80), "Note: Selection rule: minimum median prepared-call time across calibration blocks 1..5, breaking ties by smaller DPU count then smaller tasklet count. 12 primary winners + 2 supplementary Stress policy selections. Frozen receipt rule: greedy calibration, blocks 1..5, min median then D then T; no quality tuning for int8. Resource selection was performance-based under the frozen execution/correctness contract; no post-hoc approximation-quality threshold was introduced. Selections frozen before final comparison phase.")
