// Generated by thesis/synthesis/unified_v4/build.py; do not edit manually.
#text(size: 10pt, weight: "bold", "Cold-Start Planning Overhead and Amortized Execution Costs")
#v(4pt)
#{
  set text(size: 8pt)
  table(
    columns: (1fr, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr,),
    inset: 4pt,
    stroke: 0.35pt,
    table.header(repeat: true, [Workload], [Qubits ($n$)], [Cold Planning (s)], [Steady Prepared (s)], [Amortized $k=1$ (s)], [Amortized $k=10$ (s)], [Amortized $k=100$ (s)]),
    [BB84 ($n=8$)], [8], [8.05s], [0.151s], [8.20s], [0.96s], [0.232s],
    [BB84 ($n=18$)], [18], [20.43s], [0.457s], [20.89s], [2.50s], [0.661s],
    [BB84 ($n=24$)], [24], [522.90s], [15.415s], [538.32s], [67.70s], [20.644s],
    [BV ($n=8$)], [8], [28.31s], [0.222s], [28.53s], [3.05s], [0.505s],
    [BV ($n=18$)], [18], [44.64s], [0.674s], [45.31s], [5.14s], [1.121s],
    [BV ($n=24$)], [24], [474.58s], [12.820s], [487.40s], [60.28s], [17.566s],
    [EDC ($n=7$)], [7], [27.67s], [0.202s], [27.87s], [2.97s], [0.479s],
    [EDC ($n=17$)], [17], [18.89s], [0.801s], [19.69s], [2.69s], [0.990s],
    [EDC ($n=23$)], [23], [238.90s], [10.432s], [249.34s], [34.32s], [12.821s],
    [HS ($n=8$)], [8], [117.09s], [0.626s], [117.72s], [12.34s], [1.797s],
    [HS ($n=18$)], [18], [312.11s], [2.353s], [314.46s], [33.56s], [5.474s],
    [HS ($n=24$)], [24], [846.40s], [19.044s], [865.44s], [103.68s], [27.508s],
    [QRNG ($n=8$)], [8], [7.74s], [0.132s], [7.87s], [0.91s], [0.210s],
    [QRNG ($n=18$)], [18], [20.44s], [0.493s], [20.93s], [2.54s], [0.698s],
    [QRNG ($n=24$)], [24], [522.39s], [17.493s], [539.89s], [69.73s], [22.717s],
    [XOR ($n=8$)], [8], [15.67s], [0.194s], [15.87s], [1.76s], [0.351s],
    [XOR ($n=18$)], [18], [27.92s], [0.601s], [28.52s], [3.39s], [0.880s],
    [XOR ($n=24$)], [24], [468.95s], [13.426s], [482.38s], [60.32s], [18.115s],
  )
}
#v(4pt)
#text(size: 7.5pt, fill: luma(80), "Note: Cold planning time reflects single-shot offline greedy contraction path search. Steady execution reflects cached-path prepared-call time on physical UPMEM DPUs. Amortized cost per execution is computed as (T_plan + k * T_exec) / k across repeated invocations.")
