// Generated by thesis/synthesis/unified_v4/build.py; do not edit manually.
#text(size: 10pt, weight: "bold", "R-Path Preparation and Estimated Amortized Simulation Costs")
#v(4pt)
#{
  set text(size: 8pt)
  table(
    columns: (1fr, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr,),
    inset: 4pt,
    stroke: 0.35pt,
    table.header(repeat: true, [Workload], [$n$], [R-path preparation/search (s)], [Cached-path job-to-state (s)], [Estimated cost $k=1$ (s)], [$k=10$ (s)], [$k=100$ (s)]),
    [BB84], [8], [8.05], [0.151], [8.20], [0.96], [0.232],
    [BB84], [18], [20.43], [0.457], [20.89], [2.50], [0.661],
    [BB84], [24], [522.90], [15.415], [538.32], [67.70], [20.644],
    [BB84], [26], [47.67], [—], [—], [—], [—],
    [BV], [8], [28.31], [0.222], [28.53], [3.05], [0.505],
    [BV], [18], [44.64], [0.674], [45.31], [5.14], [1.121],
    [BV], [24], [474.58], [12.820], [487.40], [60.28], [17.566],
    [BV], [26], [47.07], [—], [—], [—], [—],
    [EDC], [7], [27.67], [0.202], [27.87], [2.97], [0.479],
    [EDC], [17], [18.89], [0.801], [19.69], [2.69], [0.990],
    [EDC], [23], [238.90], [10.432], [249.34], [34.32], [12.821],
    [EDC], [25], [37.59], [—], [—], [—], [—],
    [HS], [8], [117.09], [0.626], [117.72], [12.34], [1.797],
    [HS], [18], [312.11], [2.353], [314.46], [33.56], [5.474],
    [HS], [24], [846.40], [19.044], [865.44], [103.68], [27.508],
    [HS], [26], [279.80], [—], [—], [—], [—],
    [QRNG], [8], [7.74], [0.132], [7.87], [0.91], [0.210],
    [QRNG], [18], [20.44], [0.493], [20.93], [2.54], [0.698],
    [QRNG], [24], [522.39], [17.493], [539.89], [69.73], [22.717],
    [QRNG], [26], [47.63], [—], [—], [—], [—],
    [XOR], [8], [15.67], [0.194], [15.87], [1.76], [0.351],
    [XOR], [18], [27.92], [0.601], [28.52], [3.39], [0.880],
    [XOR], [24], [468.95], [13.426], [482.38], [60.32], [18.115],
    [XOR], [26], [37.58], [—], [—], [—], [—],
  )
}
#v(4pt)
#text(size: 7.5pt, fill: luma(80), "Note: R-path preparation/search is the one-time offline cost of obtaining the sealed final R contraction path; unsuccessful searches retain their measured search cost. Cached-path job-to-state measures execution from the preloaded circuit specification to an owned contiguous complete statevector with the contraction path already available. Amortized values are derived as (T_search + k T_cached) / k; they are derived cost estimates rather than separately timed cold executions. Rows with em dashes: no admitted R path; executable cached-path cost unavailable.")
