// Generated by thesis/synthesis/unified_v4/build.py; do not edit manually.
#text(size: 10pt, weight: "bold", "Unified Evaluation Campaign Accounting and Verification")
#v(4pt)
#{
  set text(size: 8pt)
  table(
    columns: (1fr, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr,),
    inset: 4pt,
    stroke: 0.35pt,
    table.header(repeat: true, [Evaluation Phase / Suite], [Planned Cells], [Planned Slots], [Issued Slots], [Successful], [Unsupported], [Dedup Avoided]),
    [Physical UPMEM Qualification], [18], [108], [108], [108], [0], [0],
    [QuEST CPU Qualification], [32], [32], [32], [32], [0], [0],
    [Simulation Qualification], [18], [108], [108], [108], [0], [0],
    [R-Path Qualification (Tiny)], [4], [4], [4], [4], [0], [0],
    [Calibration Phase C (Blocks 0..7)], [434], [2,674], [2,674], [2,674], [0], [714],
    [Topology Selection (Phase C)], [14 winners], [—], [—], [14], [0], [—],
    [Shared R-Path Search (52 cases × 128)], [52], [6,656 searches], [6,656], [6,656], [0], [—],
    [Final Comparison Phase W & S (Blocks 0..5)], [260], [1,560], [1,452], [1,452], [108], [0],
    [Total Physical UPMEM Campaign], [—], [—], [3,306], [3,306], [108], [714],
  )
}
#v(4pt)
#text(size: 7.5pt, fill: luma(80), "Note: All planned slots are fully accounted for. Physical slot executions totaled 3,306, strictly below the <= 3,406 physical slot limit. 108 final slots were not issued due to verified int8 DPU/MRAM capacity boundaries. Zero unresolved slots. Dual archives A and B verified byte-identical across all 8,279 retained files.")
