// Generated by thesis/synthesis/unified_v4/build.py; do not edit manually.
#text(size: 10pt, weight: "bold", "Unified Evaluation Campaign Accounting and Verification")
#v(4pt)
#{
  set text(size: 8pt)
  table(
    columns: (1fr, 1fr, 1fr, 1fr, 1fr,),
    inset: 4pt,
    stroke: 0.35pt,
    table.header(repeat: true, [Phase / route], [Planned slots], [Issued], [Successful], [Not issued]),
    [Physical UPMEM qualification], [108], [108], [108], [0],
    [QuEST CPU qualification], [32], [32], [32], [0],
    [Simulator qualification], [108], [108], [108], [0],
    [Calibration (blocks 0..7)], [2,674], [2,674], [2,674], [0],
    [Final: UPMEM float32], [312], [276], [276], [36],
    [Final: UPMEM int8], [312], [276], [276], [36],
    [Final: NumPy same-DAG], [312], [276], [276], [36],
    [Final: QuEST P8], [312], [312], [312], [0],
    [Final: QuEST P1], [312], [312], [312], [0],
    [Final total (blocks 0..5)], [1,560], [1,452], [1,452], [108],
    [Total physical UPMEM], [3,406], [3,334], [3,334], [72],
  )
}
#v(4pt)
#text(size: 7.5pt, fill: luma(80), "Note: Physical UPMEM issued: 3,334 ≤ 3,406 prospective ceiling. Final unsupported slots: 108; 72 are physical UPMEM allocations. Cause: no selected admissible R path for 6 maximum-width cases; both UPMEM routes and NumPy same-DAG depend on that path. R searches: 52; proposals: 6,656; selected paths: 46; no-path outcomes: 6. There were also 4 tiny qualification searches. UPMEM qualification: 54 configurations, each replayed twice per backend. Calibration: 434 cells, 714 duplicate slots avoided. Final: 260 cells. No unresolved slots or physical execution failures. The frozen retention receipt records two verified archive copies containing 8,288 files each.")
